import AutoComplete from "@/components/AutoComplete";
import Head from "next/head";

export default function Home() {
  const handleCitySelect = (cityUUID: string) => {
    console.log('Selected city UUID:', cityUUID);
  };

  return (
    <>
      <Head>
        <title>Casavo Homework</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{padding: '20px'}}>
        <h1>City Search</h1>
        <AutoComplete onSelectCity={handleCitySelect} />
      </div>
    </>
  );
}
